### ISSUE TITLE
Add v2 and v3 tabs to accounting page

### ISSUE THREAD

**Issue by ECWireless** [raid-guild/dungeon-master-v2#129]
# Overview

Before Moloch v3 data can be gathered and rendered to the accounting page, we should create 2 tabs that allow the user to switch between the Moloch v2 RaidGuild DAO data and Moloch v3 RaidGuild DAO data.

For now this should simply be visual. There's no need to render actual v3 data for this issue to be closed.

The tabs should probably be relatively discreet, and somewhere on just above the top-left of the tables.

<img width="965" alt="Screenshot 2024-04-19 at 9 15 41 AM" src="https://github.com/raid-guild/dungeon-master-v2/assets/40322776/f2125885-8a4c-45b9-a9eb-3b519b597e5f">

The default tab should be v3.

## Tasks

- [x] Add "v2" and "v3 (current)" tabs
- [x] Add v2 and v3 panels for each tab
- [ ] Store a record of the most recently viewed tab in local storage
