### ISSUE TITLE
Get transactions data for useAccountingV3

### ISSUE THREAD

**Issue by ECWireless** [raid-guild/dungeon-master-v2#134]
# Overview

Getting transaction data involves getting the proposal data associated with it, as well as some metadata (particularly when the transaction is associated with a proposal). Most likely, you can use the Gnosis Safe SDK for this, but it's not 100% certain.

Once these transactions are fetched from the Gnosis Safe SDK, you may be able to use the transaction hash to map it to proposals fetched from DAOHaus' subgraph. The current DAOHaus subgraph for v3 on Gnosis for DAO and proposal data is here: https://thegraph.com/hosted-service/subgraph/hausdao/daohaus-v3-gnosis.

## Fetch this
- Proposal id
- Title
- Member who created proposal
---------
#### DAOHAUS QUERY WITH TRANSACTION HASH
``` gql
{
  proposals(where: { processTxHash: "0xe72dda06884aa869737471bac2f5ec14756c483f830b0776b0de48363d4d3aa0"}) {
    id
    createdAt
    createdBy
    proposedBy
    processTxHash
    description
  }
}
```

**Check current transactions table columns to see exactly what metadata is needed.** It may just be "proposal," "counterparty," and "type."

https://github.com/hausdao/daohaus-v3-subgraph-sandbox

## Tasks

- [ ] Determine the best way to fetch both proposal, member, and financial data
- [ ] Fetch and format financial data in `useAccountingV3`
- [ ] Fetch and map member and proposal data to corresponding transactions
